apiVersion: v1
kind: Namespace
metadata:
  name: ns-windows-management
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: ns-windows-management
  name: ds-windows-node-config
  annotations:
    configmap.reloader.stakater.com/reload: "cm-windows-node-cronjob"
  labels:
    app: windows-node-config
spec:
  selector:
    matchLabels:
      app: windows-node-config
  template:
    metadata:
      labels:
        app: windows-node-config
    spec:
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      hostNetwork: true
      containers:
      - name: container-windows-node-cronjob
        image: mcr.microsoft.com/windows/servercore:ltsc2022
        command: ["powershell.exe"]
        args: ["-File", "C:\\tmp\\cronjob.ps1"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: script-volume
          mountPath: "C:\\tmp"
      volumes:
      - name: script-volume
        configMap:
          name: cm-windows-node-cronjob
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/os: windows
      # (Optional) Taint the node to run the daemonset on spot instances
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ns-windows-management
  name: cm-windows-node-cronjob
  annotations:
    reloader.stakater.com/match: "true"
data:
  cronjob.ps1: |
    # Function to check and set process priority
    function Set-ProcessPriority {
        param (
            [string]$processName,
            [string]$desiredPriority
        )

        $processes = Get-Process -Name $processName -ErrorAction SilentlyContinue
        if ($processes) {
            foreach ($process in $processes) {
                if ($process.PriorityClass -ne $desiredPriority) {
                    Write-Output "Setting priority of $processName (PID: $($process.Id)) to $desiredPriority" | Tee-Object -FilePath $logFilePath -Append
                    $process.PriorityClass = [System.Diagnostics.ProcessPriorityClass]::$desiredPriority
                } else {
                    Write-Output "Priority of $processName (PID: $($process.Id)) is already $desiredPriority" | Tee-Object -FilePath $logFilePath -Append
                }
            }
        } else {
            Write-Output "$processName process not found" | Tee-Object -FilePath $logFilePath -Append
        }
    }

    # Function to check and set pagefile size
    function Set-PagefileSize {
        param (
            [string]$pagefilePath,
            [int]$desiredSizeGB
        )

        $desiredSizeMB = $desiredSizeGB * 1024

        $pagefileSettings = Get-WmiObject -Query "SELECT * FROM Win32_PageFileSetting Where Name='$pagefilePath'"
        if ($pagefileSettings) {
            $currentSizeMB = $pagefileSettings.MaximumSize
            if ($currentSizeMB -ne $desiredSizeMB) {
                Write-Output "Disabling automatic pagefile management" | Tee-Object -FilePath $logFilePath -Append
                $computersys = Get-WmiObject Win32_ComputerSystem -EnableAllPrivileges;
                $computersys.AutomaticManagedPagefile = $False;
                $computersys.Put();
                Write-Output "Setting pagefile size to $desiredSizeGB GB" | Tee-Object -FilePath $logFilePath -Append
                $pagefileSettings.InitialSize = $desiredSizeMB
                $pagefileSettings.MaximumSize = $desiredSizeMB
                $pagefileSettings.Put() | Out-Null

                Write-Output "Rebooting system to apply pagefile size changes" | Tee-Object -FilePath $logFilePath -Append
                Restart-Computer -Force
            } else {
                Write-Output "Pagefile size is already $desiredSizeGB GB" | Tee-Object -FilePath $logFilePath -Append
            }
        } else {
            Write-Output "Pagefile not found at $pagefilePath" | Tee-Object -FilePath $logFilePath -Append
        }
    }

    # Function to get pagefile size
    function Get-PagefileSize {
      $pageFileSettings = Get-WmiObject -Query "SELECT * FROM Win32_PageFileSetting"
      foreach ($setting in $pageFileSettings) {
          Write-Output "-----------------------------" | Tee-Object -FilePath $logFilePath -Append
          Write-Output "Caption: $($setting.Caption)" | Tee-Object -FilePath $logFilePath -Append
          Write-Output "Description: $($setting.Description)" | Tee-Object -FilePath $logFilePath -Append
          Write-Output "Element: $($setting.Element)" | Tee-Object -FilePath $logFilePath -Append
          Write-Output "InitialSize: $($setting.InitialSize)" | Tee-Object -FilePath $logFilePath -Append
          Write-Output "MaximumSize: $($setting.MaximumSize)" | Tee-Object -FilePath $logFilePath -Append
          Write-Output "Name: $($setting.Name)" | Tee-Object -FilePath $logFilePath -Append
          Write-Output "SettingID: $($setting.SettingID)" | Tee-Object -FilePath $logFilePath -Append
          Write-Output "-----------------------------" | Tee-Object -FilePath $logFilePath -Append
      }
    }

    #
    # Main script execution
    #

    $logFilePath = "C:\ds-output.log"

    # Get computer name
    $computerName = [System.Environment]::MachineName
    Write-Output "Computer Name: $computerName" | Tee-Object -FilePath $logFilePath -Append

    $currentDateTime = Get-Date
    Write-Output "$currentDateTime - Checking and setting process priorities..." | Tee-Object -FilePath $logFilePath -Append
    Set-ProcessPriority -processName "containerd" -desiredPriority "High"
    Set-ProcessPriority -processName "kubelet" -desiredPriority "High"

    Write-Output "Checking and setting pagefile size..." | Tee-Object -FilePath $logFilePath -Append
    Get-PagefileSize
    Set-PagefileSize -pagefilePath "C:\\pagefile.sys" -desiredSizeGB 20

    $currentDateTime = Get-Date
    Write-Output "$currentDateTime - Script execution completed" | Tee-Object -FilePath $logFilePath -Append

    # Sleep for 1 hour before exiting
    Start-Sleep -Seconds 3600
    exit 0
